### ISSUE TITLE
Deploying Application Suite using automation playbooks leads to a Truststore Certificate error

### ISSUE THREAD

**Issue by alicenahas** [ibm-mas/ansible-devops#63]
## Problem Summary
It's not possible to install the Application Suite using the automation playbooks. A Truststore Certificate error, related to the certificateIssuer, happens during the install.

## Steps:
1 ./ibm/mas_devops/playbooks/ocp/provision-quickburn.yml
2 ./ibm/mas_devops/playbooks/ocp/configure-ocp.yml
3 ./ibm/mas_devops/playbooks/mas/install-suite.yml

Application Suite installation fails. Going on OpenShift console it's possible to see a "CreateContainerConfigError" on coreidp-login pod.
```
 TASK [truststore : Wait for public certificate to be ready] ******************************** 
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to gather information about Certificate(s) even after waiting for 301 seconds"}[0m
```

It was observed that, this error is happening because the certificateIssuer that remained as "None" in the Suite CR, as shown below:

![image](https://user-images.githubusercontent.com/32779810/142930503-571019df-5368-4e76-8760-6918477f6649.png)

A workaround for this is to remove this section from the CR, then deployment finishes successfully.

**Comment by stonepd** [comment]
@alequint, @andrercm - have either of you seen this issue? can you suggest a fix?

**Comment by andrercm** [comment]
I think @conradkao had a similar problem? We'll need to check why the Certificate is not getting created in first place.

**Comment by alicenahas** [comment]
@durera following the variables list:

GIT_TOKEN=
W3_USERNAME=
ARTIFACTORY_APIKEY=
MAS_CATALOG_SOURCE=
MAS_CHANNEL=
MAS_INSTANCE_ID=
MAS_ICR_CP=
MAS_ICR_CPOPEN=
CLUSTER_NAME=
CLUSTER_TYPE=
FYRE_USERNAME=
FYRE_APIKEY=
FYRE_PRODUCT_ID=
OCP_VERSION=
MAS_ENTITLEMENT_USERNAME=
MAS_ENTITLEMENT_KEY=
MAS_CONFIG_DIR=
ANSIBLE_JINJA2_NATIVE=

**Comment by durera** [comment]
Sounds like problem with the way it's handling default cluster issuer when none is provided by the user probably.

**Comment by durera** [comment]
I've been running the latest version of the playbook without a specific cluster issuer set to reproduce the same settings you are using and I'm not seeing this, so it may well be fixed in the latest release as part of the general cleanup that I went through.

**Comment by alicenahas** [comment]
Hi David. 
At first I understood it was already fixed so, I tried again and hit the same problem. Now I see that you mention that this will be fixed in the latest release. Sure, I can try again we have it.

**Comment by durera** [comment]
Cool, if you hit it again still after upgrading to the v5.0.3 release then we probably need to go into more detail about the exact inputs you are providing (and get a full set of ansible logs from the playbook run from you) so we can try to reproduce exactly what you are hitting.

**Comment by alicenahas** [comment]
@durera unfortunately issue is still happening. Just got today. If you need more info, let me know. 

![Screen Shot 2022-01-10 at 11 09 17](https://user-images.githubusercontent.com/32779810/148779702-d8708f1c-e1cc-4637-9391-2c1b519cc3d2.png)

**Comment by durera** [comment]
Any progress on this @alequint ?

**Comment by alequint** [comment]
@alicenahas as mentioned in slack this issued slipped through my fingers, never saw it before even though I am assigned and David marked me above, sorry about that!

How exactly you fix that manually? Are you creating an environment with valid certificates... I need to understand how to reproduce this issue because I have been running the roles executed by this playbook many times without problems. Can you share the environment vars you set and the logs showing the failure from your latest execution of oneclick_core ?

**Comment by alequint** [comment]
@alicenahas and the error you get is the same you originally posted last year in the description of the issue during execution of ansible collection?

```
 TASK [truststore : Wait for public certificate to be ready] ******************************** 
[0;31mfatal: [localhost]: FAILED! => {"changed": false, "msg": "Failed to gather information about Certificate(s) even after waiting for 301 seconds"}[0m
```

**Comment by alicenahas** [comment]
@alequint error is pretty much the same. Below, you can see how it shows on Suite CR. I've a Quickburn that I can share with you, where you can see this error. I'll send the credentials to you.

<img width="1051" alt="image" src="https://user-images.githubusercontent.com/32779810/172246728-fc757599-ab0c-4aa2-a126-3be8ee803aee.png">

**Comment by whitfiea** [comment]
@alicenahas I can't recreate this issue either. Can you see in the ansible playbook logs for the oneclick_core.yaml for what this value is set to:
```
"MAS Custom Cluster Issue ..... {{ custom_cluster_issuer }}"
```
The certificateIssuer block is only set in the suite CR if there is a custom cluster issuer set and that can be set based on a number of reasons.

**Comment by alicenahas** [comment]
Hi @whitfiea, this is what I can see in the execution log for Cluster Issuer: 

`"MAS Custom Cluster Issue ..... None"`

Just in case, I'm also attaching the execution [log.txt](https://github.com/ibm-mas/ansible-devops/files/8862117/log.txt).

**Comment by whitfiea** [comment]
@alicenahas What version of ansible do you have installed? `ansible-playbook --version` ? I suspect this is something in ansible that is showing None type as actually None rather than empty string. I can can make the check look for None as well so it can work in both cases. You might also want to look at running the collection in docker so you can be sure to have the expected versions installed: https://ibm-mas.github.io/ansible-devops/#running-in-docker
